import Head from "next/head";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://pokeapi.co/api/v2/type/12/`);
  const data = await res.json();

  console.log("This is a log from getServerSideProps");

  // Pass data to the page via props
  return { props: { data } };
}

type HomeProps = {
  children?: React.ReactNode;
  data: { name: string };
};

const Home: React.FC<HomeProps> = ({ data }) => {
  const handleClick = async () => {
    const res = await fetch("/api/hello");
    const data = await res.json();
    console.log(data);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>{data.name}</p>
      <button onClick={handleClick}>Click me</button>
    </div>
  );
};

export default Home;
